[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirect rules (equivalent to your vercel.json redirects)
[[redirects]]
  from = "/blog-wp/*"
  to = "/blog-wp/:splat"
  status = 200
  conditions = {Host = ["cavemotions.com"]}

# The catch-all redirect below is not needed for Next.js applications on Netlify.
# The @netlify/plugin-nextjs handles all routing, and this rule can interfere with
# dynamic routes and image optimization. It has been removed to fix image loading issues.

# Security headers (equivalent to your vercel.json headers)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
