[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules (equivalent to your vercel.json redirects)
[[redirects]]
  from = "/blog-wp/*"
  to = "/blog-wp/:splat"
  status = 200
  conditions = {Host = ["cavemotions.com"]}

# Catch-all redirect for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers (equivalent to your vercel.json headers)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
