[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # WordPress API configuration (set these in Netlify UI)
  # WORDPRESS_API_URL = "https://blog.cavemotions.com/wp-json/wp/v2"
  # NEXT_PUBLIC_WORDPRESS_API_URL = "https://blog.cavemotions.com/wp-json/wp/v2"
  # NEXT_PUBLIC_SITE_URL = "https://cavemotions.com"

# WWW canonicalization - redirect www to non-www
[[redirects]]
  from = "https://www.cavemotions.com/*"
  to = "https://cavemotions.com/:splat"
  status = 301
  force = true

# Redirect rules (equivalent to your vercel.json redirects)
[[redirects]]
  from = "/blog-wp/*"
  to = "/blog-wp/:splat"
  status = 200
  conditions = {Host = ["cavemotions.com"]}

# The catch-all redirect below is not needed for Next.js applications on Netlify.
# The @netlify/plugin-nextjs handles all routing, and this rule can interfere with
# dynamic routes and image optimization. It has been removed to fix image loading issues.

# Security headers (equivalent to your vercel.json headers)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
